version: '3.8'
services:
  cassandra:
    container_name: cassandra-db
    image: bitnami/cassandra:latest
    restart: always
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=password123
    ports:
      - "9888:9081"
    volumes:
      - c-db-data:/etc/data

volumes:
  c-db-data:
