version: '3.8'

services:
    mongo:
        container_name: mongo-db
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_DATABASE=auth
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - m-db-data:/etc/data
        networks:
            - mongo-network
        ports:
            - "27017:27017"
    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo-db
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=auth
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=pass
        depends_on:
            - mongo
        networks:
            - mongo-network
        links:
          - mongo
        ports:
          - "8888:8081"
volumes:
    m-db-data:
networks:
    mongo-network:
        driver: bridge
